import QtQuick
import Quickshell
import "../utils/FileUtil.js" as FileUtil

QtObject {
  id: store

  // JSON index generated by backend/local_music.py
  property string path: Quickshell.dataDir + "/local_music.json"
  property var settings

  property bool ready: false
  property string lastError: ""

  ListModel { id: albumsModel }
  ListModel { id: tracksModel }

  property alias albums: albumsModel
  property alias tracks: tracksModel

  // Selected album id; empty means first album.
  property string selectedAlbum: ""

  property var _albumsCache: ({}) // album_id -> tracks array

  function _clear(m) {
    while (m.count > 0) m.remove(0)
  }

  function _rebuildTracks() {
    _clear(tracksModel)
    if (!selectedAlbum || selectedAlbum.length === 0) {
      if (albumsModel.count > 0) selectedAlbum = albumsModel.get(0).album_id
    }
    var t = _albumsCache[selectedAlbum] || []
    for (var i = 0; i < t.length; i++) {
      var it = t[i]
      tracksModel.append({
        track_id: it.id || "",
        title: it.title || "",
        path: it.path || "",
        ext: it.ext || ""
      })
    }
  }

  function selectAlbum(albumId) {
    selectedAlbum = albumId
    _rebuildTracks()
  }

  function reload() {
    lastError = ""
    FileUtil.readJson(path, function(err, obj) {
      _clear(albumsModel)
      _clear(tracksModel)
      _albumsCache = ({})

      if (err) {
        lastError = err
        ready = true
        return
      }
      if (!obj) {
        ready = true
        return
      }
      if (obj.error && obj.error.length > 0) {
        lastError = obj.error
      }

      var albums = obj.albums || []
      for (var i = 0; i < albums.length; i++) {
        var a = albums[i]
        var albumId = a.id || ("album-" + i)
        albumsModel.append({
          album_id: albumId,
          title: a.title || albumId,
          track_count: a.track_count || 0
        })
        _albumsCache[albumId] = a.tracks || []
      }

      if (albumsModel.count > 0 && (!selectedAlbum || selectedAlbum.length === 0)) {
        selectedAlbum = albumsModel.get(0).album_id
      }
      _rebuildTracks()
      ready = true
    })
  }

  Timer {
    interval: 5000
    repeat: true
    running: true
    onTriggered: store.reload()
  }

  Component.onCompleted: reload()
}
